# Generated by Django 5.1.3 on 2025-09-14 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(help_text='Например: A1, B2, C1', max_length=100, unique=True, verbose_name='Название уровня')),
                ('description', models.TextField(blank=True, help_text='Описание уровня, его особенности и навыки', null=True, verbose_name='Описание уровня')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PlacementTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание теста')),
            ],
            options={
                'verbose_name': 'Placement Test',
                'verbose_name_plural': 'Placement Tests',
            },
        ),
        migrations.CreateModel(
            name='PlacementTest_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill', 'Fill in the blank'), ('translate', 'Translate'), ('listening', 'Listening')], default='mcq', max_length=20)),
                ('option_a', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант A')),
                ('option_b', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант B')),
                ('option_c', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант C')),
                ('option_d', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант D')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions_images/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='questions_audio/')),
                ('level', models.ForeignKey(blank=True, help_text='К какому уровню относится вопрос (например, A2)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='test.level', verbose_name='Уровень вопроса')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='test.placementtest', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Placement Test Вопрос',
                'verbose_name_plural': 'Placement Test Вопросы',
            },
        ),
        migrations.CreateModel(
            name='PlacementTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Имя пользователя для сертификата', max_length=255, verbose_name='Имя пользователя')),
                ('email', models.EmailField(help_text='Email для отправки сертификата', max_length=254, verbose_name='Email пользователя')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Всего вопросов')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Правильные ответы')),
                ('wrong_answers', models.PositiveIntegerField(default=0, verbose_name='Неправильные ответы')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент правильных ответов')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Набранные баллы')),
                ('level_a1_correct', models.PositiveIntegerField(default=0)),
                ('level_a2_correct', models.PositiveIntegerField(default=0)),
                ('level_b1_correct', models.PositiveIntegerField(default=0)),
                ('level_b2_correct', models.PositiveIntegerField(default=0)),
                ('level_c1_correct', models.PositiveIntegerField(default=0)),
                ('level_c2_correct', models.PositiveIntegerField(default=0)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Сертификат (PDF)')),
                ('level', models.ForeignKey(blank=True, help_text='Какой уровень был определён по результатам теста', null=True, on_delete=django.db.models.deletion.SET_NULL, to='test.level', verbose_name='Определённый уровень')),
                ('test', models.ForeignKey(help_text='Выберите тест, который прошёл пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='test.placementtest', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Результат Placement теста',
                'verbose_name_plural': 'Результаты Placement тестов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text="Название темы теста, например 'Грамматика A1'", max_length=100, unique=True, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, help_text='Описание теста и его особенности', null=True, verbose_name='Описание теста')),
                ('level', models.ForeignKey(help_text='Выберите уровень CEFR, к которому относится тест', on_delete=django.db.models.deletion.CASCADE, to='test.level', verbose_name='Уровень теста')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResultsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Имя пользователя для сертификата', max_length=255, verbose_name='Имя пользователя')),
                ('email', models.EmailField(help_text='Email для отправки сертификата', max_length=254, verbose_name='Email пользователя')),
                ('score', models.PositiveIntegerField(verbose_name='Набранные баллы')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Всего вопросов')),
                ('correct_answers', models.PositiveIntegerField(verbose_name='Правильные ответы')),
                ('wrong_answers', models.PositiveIntegerField(verbose_name='Неправильные ответы')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент правильных ответов')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Сертификат (PDF)')),
                ('test', models.ForeignKey(help_text='Выберите тест, который прошёл пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='test.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.TextField(help_text='Сам текст вопроса, который увидит пользователь', verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill', 'Fill in the blank'), ('translate', 'Translate'), ('listening', 'Listening')], default='mcq', help_text='Выберите тип вопроса', max_length=20, verbose_name='Тип вопроса')),
                ('option_a', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант A')),
                ('option_b', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант B')),
                ('option_c', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант C')),
                ('option_d', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант D')),
                ('correct_answer', models.TextField(help_text='Для MCQ укажите букву A/B/C/D, для других типов — правильный текст', verbose_name='Правильный ответ')),
                ('translation', models.CharField(blank=True, help_text='Подсказка или перевод для вопросов на перевод', max_length=255, null=True, verbose_name='Перевод / подсказка')),
                ('image', models.ImageField(blank=True, help_text='При необходимости добавьте изображение к вопросу', null=True, upload_to='questions_images/', verbose_name='Изображение')),
                ('audio_file', models.FileField(blank=True, help_text='При необходимости добавьте аудио для вопросов типа Listening', null=True, upload_to='questions_audio/', verbose_name='Аудио файл')),
                ('test', models.ForeignKey(help_text='Выберите тест, к которому относится вопрос', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='test.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['test', 'id'],
            },
        ),
    ]
